remote_theme: pmarsceill/just-the-docs
title: Conduit Documentation
permalink: pretty

# Aux links for the upper right navigation
aux_links:
  "Language and IDE on GitHub":
    - "//github.com/Energyxxer/Conduit"
  "Standard Library on GitHub":
    - "//github.com/Energyxxer/Conduit-Standard-Library"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

color_scheme: dark
