remote_theme: pmarsceill/just-the-docs
title: Conduit Documentation
permalink: pretty

# Aux links for the upper right navigation
aux_links:
  "Language and IDE on GitHub":
    - "//github.com/Energyxxer/Conduit"
  "Standard Library on GitHub":
    - "//github.com/Energyxxer/Conduit-Standard-Library"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

color_scheme: dark

collections:
  ide:
    permalink: "/ide"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    ide:
      # Give the collection a name
      name: IDE